# Generated by Django 4.2.13 on 2025-05-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user_is_admin'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
