name: Foodgram

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: foodgram
          POSTGRES_USER: foodgram_u
          POSTGRES_PASSWORD: Ujkjdjkjvrf
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run Docker Compose
        run: |
          docker-compose up --build -d

      - name: Run migrations
        run: |
          docker-compose exec backend python manage.py migrate

      - name: Stop and remove containers
        run: |
          docker-compose down
